### ISSUE TITLE
Add additional tests and benchmarks

### ISSUE THREAD

**Issue by zachbe** [zachbe/simulated-bifurcation-ising#4]

**Comment by zachbe** [comment]
The benchmarking script is failing with this error after many successful iterations.

```
Traceback (most recent call last):
  File "test_64x64_density.py", line 81, in <module>
    shuffle_spins = True
  File "/usr/local/lib/python3.6/site-packages/simulated_bifurcation-1.3.0.dev0-py3.6.egg/simulated_bifurcation/core/ising.py", line 592, in minimize
  File "/usr/local/lib/python3.6/site-packages/simulated_bifurcation-1.3.0.dev0-py3.6.egg/simulated_bifurcation/core/ising.py", line 291, in program_digital_ising
AssertionError: ERROR: Wrote 0x80 to addr 0x104c078 but read 0x0
```

**Comment by zachbe** [comment]
Another error:
```AFI PCI  Vendor ID: 0x1d0f, Device ID 0xf000
Traceback (most recent call last):
  File "test_64x64_density.py", line 81, in <module>
    shuffle_spins = True
  File "/usr/local/lib/python3.6/site-packages/simulated_bifurcation-1.3.0.dev0-py3.6.egg/simulated_bifurcation/core/ising.py", line 592, in minimize
  File "/usr/local/lib/python3.6/site-packages/simulated_bifurcation-1.3.0.dev0-py3.6.egg/simulated_bifurcation/core/ising.py", line 291, in program_digital_ising
AssertionError: ERROR: Wrote 0x100 to addr 0x102001c but read 0x0
```

It's unclear if these are just occasional PCIe write failures, or if there's an actual issue with these values. I may want to just add a "retry" option to failed writes.

**Comment by zachbe** [comment]
Even with 5 retries, it's unclear whether or not writes still fail. It may be an issue with re-initializing the FPGA repeatedly.

**Comment by zachbe** [comment]
I added a workaround to repeatedly initializing the FPGA that works! I still need to gather data for:

- Time-to-solution
- Effect of noise and mismatch

**Comment by zachbe** [comment]
Added data for noise and time-to-solution! I just need to process it.

**Comment by zachbe** [comment]
Done!
